export const products = [
    {
      id: 1,
      slug: "galaxy-a35-5g",
      name: "Galaxy A35 5G",
      image: "/images/iPhone-15-Plus.jpg",
      price: 29800,
      originalPrice: 34000,
    },
    {
      id: 2,
      slug: "iphone-15-plus",
      name: "iPhone 15 Plus",
      image: "/images/iPhone-15.webp",
      price: 120000,
    },
    {
      id: 3,
      slug: "samsung-galaxy-s23",
      name: "Samsung Galaxy S23",
      image: "/images/Pixel-8.webp",
      price: 74999,
      originalPrice: 84999,
    },
    {
      id: 4,
      slug: "oneplus-11",
      name: "OnePlus 11",
      image: "/images/Redmi-Note-14-Pro-Plus-5G-Phantom-Purple-2044.webp",
      price: 52999,
      originalPrice: 59999,
    },
    {
      id: 5,
      slug: "iphone-14-pro-max",
      name: "iPhone 14 Pro Max",
      image: "/images/Pixel-8.webp",
      price: 149999,
    },
    {
      id: 6,
      slug: "xiaomi-mi-11",
      name: "Xiaomi Mi 11",
      image: "/images/iPhone-15-Plus.jpg",
      price: 45999,
      originalPrice: 49999,
    },
    {
      id: 7,
      slug: "realme-gt-2-pro",
      name: "Realme GT 2 Pro",
      image: "/images/Redmi-Note-14-Pro-Plus-5G-Phantom-Purple-2044.webp",
      price: 34999,
      originalPrice: 37999,
    },
    {
      id: 8,
      slug: "google-pixel-7-pro",
      name: "Google Pixel 7 Pro",
      image: "/images/Pixel-8.webp",
      price: 89999,
    },
    {
      id: 9,
      slug: "oppo-reno-8",
      name: "Oppo Reno 8",
      image: "/images/iPhone-15.webp",
      price: 22999,
      originalPrice: 25999,
    },
    {
      id: 10,
      slug: "vivo-v23e",
      name: "Vivo V23e",
      image: "/images/iPhone-15.webp",
      price: 19999,
      originalPrice: 21999,
    },
    {
      id: 11,
      slug: "huawei-p50-pro",
      name: "Huawei P50 Pro",
      image: "/images/iPhone-15.webp",
      price: 74999,
      originalPrice: 79999,
    },
    {
      id: 12,
      slug: "sony-xperia-1-iii",
      name: "Sony Xperia 1 III",
      image: "/images/iPhone-15.webp",
      price: 99999,
      originalPrice: 104999,
    },
    // {
    //   id: 13,
    //   slug: "asus-rog-phone-5",
    //   name: "Asus ROG Phone 5",
    //   image: "/images/asus-rog-phone-5.jpg",
    //   price: 79999,
    // },
    // {
    //   id: 14,
    //   slug: "lenovo-legion-phone-duel-2",
    //   name: "Lenovo Legion Phone Duel 2",
    //   image: "/images/lenovo-legion-phone-duel-2.jpg",
    //   price: 64999,
    // },
    // {
    //   id: 15,
    //   slug: "moto-g100",
    //   name: "Motorola G100",
    //   image: "/images/moto-g100.jpg",
    //   price: 34999,
    // },
  ]
  export const menuItems = [
    {
      label: "Phones & Tablets",
      link: "/category/phones-tablets",
      subItems: [
        { label: "iPad & TAB", link: "/category/phones-tablets/ipad-and-tab" },
        { label: "iPhone", link: "/category/phones-tablets/iphone" },
        { label: "SAMSUNG", link: "/category/phones-tablets/samsung" },
        { label: "Google", link: "/category/phones-tablets/google" },
        { label: "Xiaomi", link: "/category/phones-tablets/xiaomi" },
        { label: "Amazon", link: "/category/phones-tablets/amazon" },
        { label: "OnePlus", link: "/category/phones-tablets/oneplus" },
        { label: "Nokia", link: "/category/phones-tablets/nokia" },
        { label: "realme", link: "/category/phones-tablets/realme" },
        { label: "NOTHING", link: "/category/phones-tablets/nothing" },
        { label: "HUAWEI", link: "/category/phones-tablets/huawei" },
        { label: "Infinix", link: "/category/phones-tablets/infinix" },
        { label: "OPPO", link: "/category/phones-tablets/oppo" },
        { label: "Tecno", link: "/category/phones-tablets/tecno" },
        { label: "vivo", link: "/category/phones-tablets/vivo" },
        { label: "Motorola", link: "/category/phones-tablets/motorola" },
        { label: "ASUS", link: "/category/phones-tablets/asus" },
        { label: "ZTE", link: "/category/phones-tablets/zte" },
        { label: "Balmuda", link: "/category/phones-tablets/balmuda" },
      ],
    },
    {
      label: "Sound Equipment",
      link: "/category/sound-equipment",
      subItems: [
        { label: "Airpods", link: "/category/sound-equipment/airpods" },
        { label: "Overhead Headphones", link: "/category/sound-equipment/overhead-headphones" },
        { label: "Wired Headphone", link: "/category/sound-equipment/wired-headphone" },
        { label: "Wireless Headphone", link: "/category/sound-equipment/wireless-headphone" },
        { label: "Speakers", link: "/category/speakers" },
      ],
    },
    {
      label: "Laptop & Desktop",
      link: "/category/laptop-and-desktop",
      subItems: [
        { label: "Gaming Laptop", link: "/category/laptop-and-desktop/gaming-laptop" },
        { label: "MacBook", link: "/category/laptop-and-desktop/macbook" },
        { label: "iMac", link: "/category/imac" },
        { label: "Mac mini", link: "/category/mac-mini" },
        { label: "Mac Studio", link: "/category/mac-studio" },
        { label: "Ultrabook", link: "/category/laptop-and-desktop/ultrabook" },
        { label: "Business Class Laptop", link: "/category/laptop-and-desktop/business-class-laptop" },
        { label: "New 14th Gen 2024", link: "/category/laptop-and-desktop/new-14th-gen-2024" },
      ],},
      {
        label: "Laptop & Desktop",
        link: "/category/laptop-and-desktop",
        subItems: [
          { label: "Gaming Laptop", link: "/category/laptop-and-desktop/gaming-laptop" },
          { label: "MacBook", link: "/category/laptop-and-desktop/macbook" },
          { label: "iMac", link: "/category/imac" },
          { label: "Mac mini", link: "/category/mac-mini" },
          { label: "Mac Studio", link: "/category/mac-studio" },
          { label: "Ultrabook", link: "/category/laptop-and-desktop/ultrabook" },
          { label: "Business Class Laptop", link: "/category/laptop-and-desktop/business-class-laptop" },
          { label: "New 14th Gen 2024", link: "/category/laptop-and-desktop/new-14th-gen-2024" },
        ],
      },
      {
        label: "Sound Equipment",
        link: "/category/sound-equipment",
        subItems: [
          { label: "Airpods", link: "/category/sound-equipment/airpods" },
          { label: "Overhead Headphones", link: "/category/sound-equipment/overhead-headphones" },
          { label: "Wired Headphone", link: "/category/sound-equipment/wired-headphone" },
          { label: "Wireless Headphone", link: "/category/sound-equipment/wireless-headphone" },
          { label: "Speakers", link: "/category/speakers" },
        ],
      },
      {
        label: "Sound Equipment",
        link: "/category/sound-equipment",
        subItems: [
          { label: "Airpods", link: "/category/sound-equipment/airpods" },
          { label: "Overhead Headphones", link: "/category/sound-equipment/overhead-headphones" },
          { label: "Wired Headphone", link: "/category/sound-equipment/wired-headphone" },
          { label: "Wireless Headphone", link: "/category/sound-equipment/wireless-headphone" },
          { label: "Speakers", link: "/category/speakers" },
        ],
      },
      {
        label: "Sound Equipment",
        link: "/category/sound-equipment",
        subItems: [
          { label: "Airpods", link: "/category/sound-equipment/airpods" },
          { label: "Overhead Headphones", link: "/category/sound-equipment/overhead-headphones" },
          { label: "Wired Headphone", link: "/category/sound-equipment/wired-headphone" },
          { label: "Wireless Headphone", link: "/category/sound-equipment/wireless-headphone" },
          { label: "Speakers", link: "/category/speakers" },
        ],
      },
    ];  

    export const brands = [
    { id: 1, name: "Dell", img: "/images/Dell.png",},
    { id: 2, name: "msi", img: "/images/msi.png",  },
    { id: 3, name: "Boat", img: "/images/Boat-Logo-5471.jpg", },
    { id: 4, name: "titan", img: "/images/Titan-Logo-7052.jpg", link: "/brands/xiaomi" },
    { id: 5, name: "K-doo", img: "/images/K-Doo-6655.png", link: "/brands/google" },
    { id: 6, name: "Huawei", img: "/images/Huawei-3570.png", link: "/brands/huawei" },
    { id: 7, name: "Realme", img: "/images/realme-logo-8426.png", link: "/brands/realme" },
    { id: 8, name: "Fitbit", img: "/images/Fitbit-2950.png", link: "/brands/fitbit" },
    { id: 9, name: "Anker", img: "/images/Anker-9579.png", link: "/brands/anker" },
    { id: 10, name: "Acer", img: "/images/acer-logo-4267.jpg", link: "/brands/vivo" },
    { id: 11, name: "Spigen", img: "/images/Spigen-1509.png", link: "/brands/vivo" },
    { id: 12, name: "Pitaka", img: "/images/PITAKA-4288.jpg", link: "/brands/vivo" },
    
    ];

    
export const relatedProducts = [
  {
    id: 1,
    name: "iPhone 14 Pro",
    price: "130000৳",
    originalPrice: "150000৳",
    image: "/images/iPhone-14-Purple-6116.webp",
    link: "/product/iphone-14-pro",
  },
  {
    id: 2,
    name: "iPhone 13",
    price: "65000৳",
    originalPrice: "85000৳",
    image: "/images/13iphone.webp",
    link: "/product/iphone-13",
  },
  {
    id: 3,
    name: "iPhone 12 Pro",
    price: "TBA",
    image: "/images/12Pro.webp",
    link: "/product/iphone-12pro-official",
  },
  {
    id: 4,
    name: "iPhone 12 Pro Max",
    price: "TBA",
    image: "/images/iPhone-15-Plus.jpg",
    link: "/product/iphone-12-pro-max-official",
  },
  {
    id: 5,
    name: "iPhone 11",
    price: "44000৳",
    originalPrice: "62500৳",
    image: "/images/iPhone-11-Black-5949.webp",
    link: "/product/iphone-11",
  },
  {
    id: 6,
    name: "iPhone 16 Pro",
    price: "134500৳",
    originalPrice: "175000৳",
    image: "/images/16Promax.jpg",
    link: "/product/iphone-16-pro",
  },
  {
    id: 7,
    name: "iPhone 14",
    price: "TBA",
    image: "/images/iPhone-14-Purple-6116.webp",
    link: "/product/iphone-14",
  },
  {
    id: 8,
    name: "iPhone 16 Pro",
    price: "134500৳",
    originalPrice: "175000৳",
    image: "/images/iPhone-16-Pro-Max---16-Pro-Black-Titanium-2734.webp",
    link: "/product/iphone-16-pro",
  },
  {
    id: 9,
    name: "iPhone 16 Pro",
    price: "134500৳",
    originalPrice: "175000৳",
    image: "/images/12Pro.webp",
    link: "/product/iphone-16-pro",
  },
];

 export const colorOptions = [
  {
    name: "Desert Titanium",
    image: "/images/iPhone-16-Pro-Max---16-Pro-Desert-Titanium-1929.jpg",
  },
  {
    name: "Black Titanium",
    image: "/images/iPhone-16-Pro-Max---16-Pro-Black-Titanium-2734.webp",
  },
  {
    name: "White Titanium",
    image: "/images/iPhone-16-Pro-Max---16-Pro-White-Titanium-5148.jpg",
  },
  {
    name: "Natural Titanium",
    image: "/images/iPhone-16-Pro-Max---16-Pro-Natural-Titanium-3560.jpg",
  },
];